# Generated by Django 4.2 on 2025-05-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('id_licitacion', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('tipo', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('moneda', models.CharField(max_length=10)),
                ('tipo_presupuesto', models.CharField(max_length=100)),
                ('tipo_monto', models.CharField(max_length=100)),
                ('monto', models.CharField(max_length=100)),
                ('organismo', models.TextField()),
            ],
        ),
    ]
